name: Build KMP Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
      ANDROID_NDK_VERSION: 25.2.9519653

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: |
          sdkmanager --install "ndk;$ANDROID_NDK_VERSION"
          echo "NDK installed at $ANDROID_HOME/ndk/$ANDROID_NDK_VERSION"

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

        
      - name: Assemble Debug APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: composeApp/build/outputs/apk/debug/composeApp-release.apk